POST  http://localhost:3001/api/UserC
Content-Type: application/json

{
    "user":"Abner",
    "password":"123"
}

###
GET http://localhost:3001/api/User
Content-Type: application/json


###

GET http://localhost:3001/api/UserP
Content-Type: application/json