POST  http://localhost:3001/api/UserC
Content-Type: application/json

{
    "user":"stopss",
    "password":"12344s",
    "userName":"GAPs",
    "email":"ohhhs",
    "office":"Administrador"
}

###
GET http://localhost:3001/api/User
Content-Type: application/json


###

GET http://localhost:3001/api/UserS/Abner de 
Content-Type: application/json
### nao uso

###
PUT http://localhost:3001/api/UserA/65b71e00a076ee4986d58a39
Content-Type: application/json

{
  "user":"stops",
  "password":"12344",
  "userName":"GAP",
  "email":"ohhhh",
  "office":"Administrador"
}

###
DELETE http://localhost:3001/api/UserD/65b48911502dddc6c4f2426a
Content-Type: application/json

###
post http://localhost:3001/api/Login
Content-Type: application/json

{
    "user":"Abner Quintilianos",
    "password":"Negão"
}

##############################################################################################################
post http://localhost:3001/api/Produto/Create
Content-Type: application/json

{
  "marca": "Oakley",
  "nome": "Juliete",
  "valor": 200,
  "tipo": "Óculos ",
  "Img": 454654,
  "Cores": [
    {
      "Cor": "roxo",
      "Tamanhos": [
        {
          "Tamanho": "-",
          "Quantidade": 20
        }
      ]
    },
    {
      "Cor": "laranja",
      "Tamanhos": [
        {
          "Tamanho": "-",
          "Quantidade": 40
        }
      ]
    }
  ]
}

###bahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
get http://localhost:3001/api/Produto/Faltando
Content-Type: application/json

###
get http://localhost:3001/api/Produto
Content-Type: application/json

###
get http://localhost:3001/api/Produto/Compra
Content-Type: application/json

###
PUT  http://localhost:3001/api/Produto/Atualizando/65601c6bed21a22cf38a1341
Content-Type:  application/json

{
  "Cores": [
    {
      "Cor": "roxo",
      "Tamanhos": [
        {
          "Tamanho": "-",
          "Quantidade": 30
        }
      ]
    },
    {
      "Cor": "laranja",
      "Tamanhos": [
        {
          "Tamanho": "-",
          "Quantidade": 30
        }
      ]
    }
  ],
  "marca": "Oakley",
  "nome": "Juliete",
  "valor": 220,
  "tipo": "Óculos ",
  "Img": 454654
}

###
DELETE http://localhost:3001/api/Produto/Deletando/655e1cafdfa70bd7a988fb91
Content-Type: application/json

##########################################################################################################################

POST http://localhost:3001/api/Tarefa/Create
Content-Type: application/json
{
  "conteudo":"Limpar vidros da entrada"
}

###
get http://localhost:3001/api/Tarefa
Content-Type: application/json

###
delete http://localhost:3001/api/Tarefa/Deletando/656e05eb76a455b4d93ff174
Content-Type: application/json